Initial commit of VNC support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -687,6 +687,7 @@ CFG_EGLFS_MALI=no
 CFG_EGLFS_VIV=no
 CFG_DIRECTFB=auto
 CFG_LINUXFB=auto
+CFG_VNC=auto
 CFG_KMS=auto
 CFG_LIBUDEV=auto
 CFG_LIBINPUT=auto
@@ -1835,6 +1836,13 @@ while [ "$#" -gt 0 ]; do
             UNKNOWN_OPT=yes
         fi
         ;;
+    vnc)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            CFG_VNC="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
     kms)
         if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
             CFG_KMS="$VAL"
@@ -2635,6 +2643,9 @@ Additional options:
 
     -no-linuxfb ........ Do not compile Linux Framebuffer support.
  *  -linuxfb ........... Compile Linux Framebuffer support.
+
+    -no-vnc ............ Do not compile VNC support.
+ *  -vnc ............... Compile VNC support.
 
     -no-kms ............ Do not compile KMS support.
  *  -kms ............... Compile KMS support (Requires EGL).
@@ -5240,6 +5251,7 @@ ORIG_CFG_XCB="$CFG_XCB"
 ORIG_CFG_EGLFS="$CFG_EGLFS"
 ORIG_CFG_DIRECTFB="$CFG_DIRECTFB"
 ORIG_CFG_LINUXFB="$CFG_LINUXFB"
+ORIG_CFG_VNC="$CFG_VNC"
 ORIG_CFG_KMS="$CFG_KMS"
 
 if [ "$CFG_LIBUDEV" != "no" ]; then
@@ -5509,6 +5521,14 @@ if [ "$CFG_LINUXFB" != "no" ]; then
     fi
 fi
 
+if [ "$CFG_VNC" != "no" ]; then
+    if [ "$CFG_VNC" = "yes" ] && [ "$XPLATFORM_MINGW" = "yes" ]; then
+        echo " VNC support cannot be enabled on Windows"
+        exit 101
+    fi
+    CFG_VNC=yes
+fi   
+
 if [ "$CFG_KMS" != "no" ]; then
     if compileTest qpa/kms "KMS"; then
         CFG_KMS=yes
@@ -5690,14 +5710,17 @@ fi
 if [ "$CFG_LINUXFB" = "yes" ]; then
     QT_CONFIG="$QT_CONFIG linuxfb"
 fi
+if [ "$CFG_VNC" = "yes" ]; then
+    QT_CONFIG="$QT_CONFIG vnc"
+fi
 if [ "$CFG_KMS" = "yes" ]; then
     QT_CONFIG="$QT_CONFIG kms"
 fi
 
 if [ "$XPLATFORM_MAC" = "no" ] && [ "$XPLATFORM_MINGW" = "no" ] && [ "$XPLATFORM_QNX" = "no" ] && [ "$XPLATFORM_ANDROID" = "no" ] && [ "$XPLATFORM_HAIKU" = "no" ]; then
-    if [ "$CFG_XCB" = "no" ] && [ "$CFG_EGLFS" = "no" ] && [ "$CFG_DIRECTFB" = "no" ] && [ "$CFG_LINUXFB" = "no" ] && [ "$CFG_KMS" = "no" ]; then
+    if [ "$CFG_XCB" = "no" ] && [ "$CFG_EGLFS" = "no" ] && [ "$CFG_DIRECTFB" = "no" ] && [ "$CFG_LINUXFB" = "no" ] && [ "$CFG_VNC" = "no" ] && [ "$CFG_KMS" = "no" ]; then
         if [ "$QPA_PLATFORM_GUARD" = "yes" ] &&
-            ( [ "$ORIG_CFG_XCB" = "auto" ] || [ "$ORIG_CFG_EGLFS" = "auto" ] || [ "$ORIG_CFG_DIRECTFB" = "auto" ] || [ "$ORIG_CFG_LINUXFB" = "auto" ] || [ "$ORIG_CFG_KMS" = "auto" ] ); then
+            ( [ "$ORIG_CFG_XCB" = "auto" ] || [ "$ORIG_CFG_EGLFS" = "auto" ] || [ "$ORIG_CFG_DIRECTFB" = "auto" ] || [ "$ORIG_CFG_LINUXFB" = "auto" ] || [ "$ORIG_CFG_VNC" = "auto" ] || [ "$ORIG_CFG_KMS" = "auto" ] ); then
         echo "No QPA platform plugin enabled!"
         echo " If you really want to build without a QPA platform plugin you must pass"
         echo " -no-qpa-platform-guard to configure. Doing this will"
@@ -7112,6 +7135,7 @@ report_support "      EGLFS Mali ........." "$CFG_EGLFS_MALI"
 report_support "      EGLFS Raspberry Pi ." "$CFG_EGLFS_BRCM"
 report_support "      EGLFS X11 .........." "$CFG_EGL_X"
 report_support "    LinuxFB .............." "$CFG_LINUXFB"
+report_support "    VNC .................." "$CFG_VNC"
 report_support "    XCB .................." "$CFG_XCB" system "system library" qt "bundled copy"
 if [ "$CFG_XCB" != "no" ]; then
     report_support "      EGL on X ..........." "$CFG_EGL_X"
